### PR TITLE
Completed derivation of hypergeometric distribution

### LINKED ISSUE #1: Urn of white and black marbles - pg3

### PR DESCRIPTION
**Pull request by openerror**
Closes #1 Urn of black and white marbles.

### CODE REVIEW

**Comment by DanielSank** [comment]
Thank you for this pull request ^.^

I am puzzled by one bit of the explanation:

> the binomial coefficient is applicable, because we are selecting indistinguishable objects without replacement.

The binomial coefficient is appropriate when selecting identical objects *with* replacement. Could you explain, please?

**Comment by openerror** [comment]
Hey there, thanks for the comment! I just consulted my probability textbook, and I'm sure that the binomial coefficient applies when selecting identical objects _without_ replacement. Consider "N choose r" = N! / r! / (N-r)!; the nominator would be N^r instead of N!, if with replacement.

**Comment by DanielSank** [comment]
@openerror Hmmm, ok I must be misunderstanding something. I'll try to have another look this evening.

**Comment by DanielSank** [comment]
Blarg. I probably won't get to this until the weekend :-P

**Comment by openerror** [comment]
Happy labor day weekend! Any updates on the pull request :)?

**Comment by DanielSank** [comment]
I spent some time thinking about it his evening and I'm still not convinced. The explanation in the pull request seems close, but it leaves out enough detail that I don't quite see it yet.

**Comment by DanielSank** [comment]
Ok, thinking about it more last night, I see why the result is what it is, and I see what you're getting at in the explanation. I still think it could a bit more clear though. I'll write a more detailed response this evening.

**Comment by DanielSank** [comment]
Hi! I took the "brute force" approach you explained, expanded the discussion a bit, and merged it into master. I used a merge commit, and somehow that didn't automatically close the pull request, so I'm closing it manually now.

Thank you for the contribution! I would like to create a list of contributors and add it to the beginning of the document. Shall I use your real name of your GitHub name?

**Pull request closed without merging**
