### PR TITLE
Added problem from pg 80, made changes as requested by Daniel 

### PR DESCRIPTION
**Pull request by JdoesScience**
Made the required changes Daniel asked for by removing colour and updating file name and headers with appropriate page numbers. Sorry for any headache caused, still a bit new to using github with access tokens.

### CODE REVIEW

**Review by DanielSank — APPROVED** [review]
Thank you for this contribution.

There are a few minor style guide things here that I'll fix up in a subsequent commit.

**Comment by JdoesScience** [comment]
> Thank you for this contribution.
> 
> There are a few minor style guide things here that I'll fix up in a subsequent commit.

@DanielSank 
Hey no problem, thank you for letting me contribute to this project and for approving the merge request!
I'm thinking I may add one or two more solutions this weekend if I've got some time. Would you like me to wait until you fix the minor style guide things or would you be able to list them here so I can make them (so there's less work on your part!)? Either way there's no rush, I'm sure you're extremely busy! Just let me know!

**Comment by DanielSank** [comment]
I've updated the README with a style guide. Please follow it :-)

Thanks again for contributing to this project. By the way, I am considering consolidating this and a few of my other textbook solutions repos into a GitHub organization.

**Comment by JdoesScience** [comment]
> I've updated the README with a style guide. Please follow it :-)
> 
> Thanks again for contributing to this project. By the way, I am considering consolidating this and a few of my other textbook solutions repos into a GitHub organization.

@DanielSank Awesome, thank you Daniel! I'll do my best! 
My pleasure, I have more answers incoming and on the way this week, I apologise if you're already extremely busy, just thought I would let you know in advance! Also regarding style, what are your criteria involving questions that ask you to "argue" certain points? As an example, on pg.73 of the third edt of the book, VK wants you to argue that neutrons in a reactor is a Markov process. Do you have any particular way that questions like that need to be formatted? Secondly, for "matrix" and "linear algebra" type questions like on pages 103 and 120, do you have a particular way you want the matrices done? Also, it will likely require one of the additional math packages (amssymb) because VK uses \mathbb to denote the matrices.... for some reason. Just wanted to point them out since those are some of the questions I'm converting to LATEX right now. 

That would be AWESOME if you consolidated them into a GitHub Organization and I would be happy to contribute in whatever way I can! I also have solutions from Feynman and Hibbs "Quantum Mechanics and Path Integral"  in my repo (it's the one with the stupid name and spelling error), feel free to pull that and add it too! It is woefully incomplete though but most of the solutions are written down and sitting here next to me, I have them scanned in pdf which I will send to you at some point if it helps, just haven't had time to convert them to Latex. 

If it's alright with you, I'm going to send you an email at some point this week along with the solutions I have in case you or you know someone who would be super interested in converting them to latex (and also double-checking that I've done them currently haha, I'm only human and prone to mistakes!) 

Hope you are taking care! Thanks again for doing this and hosting and such!

**Pull request merged**
